version: 1.3.0.{build}
branches:
  only:
  - gabcm-dev
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore src\Mpv.NET\Mpv.NET.csproj
build:
  project: src/Mpv.NET/Mpv.NET.csproj
  parallel: true
  verbosity: normal
before_package:
- cmd: >-
    nuget spec src\Mpv.NET\Mpv.NET.csproj

    dotnet pack src\Mpv.NET\Mpv.NET.csproj
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
deploy:
- provider: NuGet
  symbol_server: https://ci.appveyor.com/nuget/gabcm-0slksit4752a/api/v2/package
  api_key:
    secure: yFHdIf3nvAamT/Vi4/n2aaehcYp2zg3vLYO8nV+sIfg=
  artifact: /.*\.nupkg/
  on:
    branch: gabcm-dev
on_success:
- pwsh: >-
    $Form = @{
        text = "Le build Mpv NET -lib- a faite"
    }


    $formJson = ConvertTo-Json $Form


    Invoke-RestMethod -Uri "https://hooks.slack.com/services/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" -Method Post -Body $formJson -ContentType 'application/json'
on_failure:
- pwsh: >-
    $Form = @{
        text = "Le build Mpv NET -lib- a PAS faite"
    }


    $formJson = ConvertTo-Json $Form


    Invoke-RestMethod -Uri "https://hooks.slack.com/services/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" -Method Post -Body $formJson -ContentType 'application/json'